Laney Graduate School:
  workflow:
   - laney_graduate_school
  approving:
   - thairst # Tamika Hairston
   - twrig31 # Tracey Wright
   - unilsso # Ulf Nilsson
   - rlwebb # Renee Webb
Emory College:
  approving:
   - cbeard4 # Carlee Beard
Candler School of Theology:
  approving:
   - shart # Shelly Hart
   - ksgarne # Kelly Garner Shannon
Rollins School of Public Health:
  approving:
   - tezprox
   - rollinsadmin2
