Laney Graduate School:
  workflow:
   - laney_graduate_school
  approving:
   - thairst # Tamika Hairston
   - twrig31 # Tracey Wright
   - unilsso # Ulf Nilsson
   - rlwebb # Renee Webb
Emory College:
  approving:
   - cbeard4 # Carlee Beard
Candler School of Theology:
  approving:
   - shart # Shelly Hart
   - ksgarne # Kelly Garner Shannon
Applied Epidemiology:
  approving:
   - letompk
   - malperi
   - rfreem2
Applied Public Health Informatics:
  approving:
   - letompk
   - malperi
   - rfreem2
Behavioral Sciences and Health Education:
  approving:
    - mcrios
    - rfreem2
Biostatistics:
  approving:
    - msherre
    - rfreem2
Environmental Health - MPH:
  approving:
    - ascarl
    - rfreem2
Environmental Health Epidemiology - MPH & MSPH:
  approving:
    - ascarl
    - rfreem2
Epidemiology:
  approving:
    - jtenley
    - nferlan
    - rfreem2
Global Environmental Health - MPH:
  approving:
    - ascarl
    - rfreem2
Global Epidemiology:
  approving:
   - jtenley
   - nferlan
   - rfreem2
Health Care Outcomes Management:
  approving:
   - letompk
   - malperi
   - rfreem2
Health Policy and Management:
  approving:
   - kwollen
   - rfreem2
Hubert Department of Global Health:
  approving:
   - tnash
   - ftraven
   - rfreem2
Management Science:
  approving:
   - letompk
   - malperi
   - rfreem2
Maternal and Child Health Epidemiology:
  approving:
   - letompk
   - malperi
   - rfreem2
Prevention Science:
  approving:
   - letompk
   - malperi
   - rfreem2
Public Health Informatics:
  approving:
   - msherre
   - rfreem2
