inherit_gem:
  bixby: bixby_default.yml

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
