inherit_gem:
  bixby: bixby_default.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Lint/Void:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Rails/FindBy:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

# complaining about the Capfile name. Wants it to be snake_case - re-enabling, should be fixed by updated Bixby 
Style/FileName:
  Enabled: true

Style/Semicolon:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/AlignParameters:
  Exclude:
    - 'app/models/etd.rb'

Layout/ClosingParenthesisIndentation:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/javascripts/jasmine_spec.rb'

RSpec/NestedGroups:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
