language: ruby
cache: bundler
sudo: false
services:
  - redis-server
jdk:
  - oraclejdk8
rvm:
  - 2.3.3
  - 2.3.4
script:
  - RAILS_ENV=test bundle exec rake db:setup --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rubocop
  - bundle exec rake ci
