terms:
    - id: Accounting
      term: Accounting
    - id: Finance
      term: Finance
    - id: Information Systems & Operations Management
      term: Information Systems & Operations Management
    - id: Marketing
      term: Marketing
    - id: Organization & Management
      term: Organization & Management
