terms:
    - id: Divinity
      term: Divinity
    - id: Ministry
      term: Ministry
    - id: Pastoral Counseling
      term: Pastoral Counseling
    - id: Theological Studies
      term: Theological Studies
      