terms:
    - id: Environmental Health - MPH
      term: Environmental Health - MPH
    - id: Environmental Health Epidemiology -  MSPH
      term: Environmental Health Epidemiology -  MSPH
    - id: Global Environmental Health - MPH
      term: Global Environmental Health - MPH