terms:
    - id: Environmental Health - MPH
      term: Environmental Health - MPH
    - id: Environmental Health Epidemiology - MPH & MSPH
      term: Environmental Health Epidemiology - MPH & MSPH
    - id: Global Environmental Health - MPH
      term: Global Environmental Health - MPH
