terms:
    - id: Applied Epidemiology
      term: Applied Epidemiology
    - id: Applied Public Health Informatics
      term: Applied Public Health Informatics
    - id: Health Care Outcomes Management
      term: Health Care Outcomes Management
    - id: Management Science
      term: Management Science
    - id: Maternal and Child Health Epidemiology
      term: Maternal and Child Health Epidemiology
    - id: Prevention Science
      term: Prevention Science