terms:
    - id: 'Fall 2017'
      term: 'Fall 2017'
    - id: 'Spring 2018'
      term: 'Spring 2018'
    - id: 'Summer 2018'
      term: 'Summer 2018'
    - id: 'Fall 2018'
      term: 'Fall 2018'
    - id: 'Spring 2019'
      term: 'Spring 2019'
    - id: 'Summer 2019'
      term: 'Summer 2019'
    - id: 'Fall 2019'
      term: 'Fall 2019'
    - id: 'Spring 2020'
      term: 'Spring 2020'
    - id: 'Summer 2020'
      term: 'Summer 2020'
    - id: 'Fall 2020'
      term: 'Fall 2020'