terms:
    - id: 'English'
      term: 'English'
    - id: 'Spanish'
      term: 'Spanish'
    - id: 'French'
      term: 'French'
    - id: 'German'
      term: 'German'
    - id: 'Italian'
      term: 'Italian'
    - id: 'Icelandic'
      term: 'Icelandic'