terms:
    - id: Clinical Psychology
      term: Clinical Psychology
    - id: Cognition and Development
      term: Cognition and Development
    - id: Neuroscience and Animal Behavior
      term: Neuroscience and Animal Behavior
