terms:
    - id: American Religious Cultures
      term: American Religious Cultures
    - id: Ethics and Society
      term: Ethics and Society
    - id: Hebrew Bible
      term: Hebrew Bible
    - id: Historical Studies in Theology and Religion
      term: Historical Studies in Theology and Religion
    - id: Jewish Religious Cultures
      term: Jewish Religious Cultures
    - id: New Testament
      term: New Testament
    - id: Person, Community and Religious Life
      term: Person, Community and Religious Life
    - id: Theological Studies
      term: Theological Studies
    - id: West and South Asian Religions
      term: West and South Asian Religions
