terms:
    - id: '5670'
      term: 'Dentistry'
    - id: '566'
      term: 'Health Sciences'
    - id: '992'
      term: 'Oncology'
    - id: '383'
      term: 'Toxicology'
    - id: '213'
      term: 'Psychology'
    - id: '576'
      term: 'Surgery'
    - id: '496'
      term: 'Alternative Medicine'
    - id: '382'
      term: 'Physical Therapy'
    - id: '442'
      term: 'Adolescent Development'
    - id: '986'
      term: "Women's Health"
