terms:
    - id: Behavioral Sciences & Health Education - MPH
      term: Behavioral Sciences & Health Education - MPH
    - id: Biostatistics and Bioinformatics
      term: Biostatistics and Bioinformatics
    - id: Environmental Health
      term: Environmental Health
    - id: Epidemiology
      term: Epidemiology
    - id: Executive Masters of Public Health - MPH
      term: Executive Masters of Public Health - MPH
    - id: Health Policy and Management - MSPH
      term: Health Policy and Management - MSPH
    - id: Hubert Department of Global Health - MPH
      term: Hubert Department of Global Health - MPH 
